name: Test Sticky Comment

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test-comment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Post sticky comment (first)
        uses: ./
        with:
          key: 'test-pr-comment'
          body: test comment (will be updated with next step)

      - name: Post sticky comment
        uses: ./
        with:
          key: 'test-pr-comment'
          body: |
            ## 🧪 Test Comment

            This is a test of the sticky comment action!

            - PR Number: #${{ github.event.pull_request.number }}
            - SHA: ${{ github.event.pull_request.head.sha }}
            - Timestamp: ${{ github.event.pull_request.updated_at }}

            This comment should update on each push, not create duplicates.

      - name: Post another sticky comment with different key
        uses: ./
        with:
          key: 'build-info'
          body: |
            ## 📦 Build Information

            - Branch: ${{ github.head_ref }}
            - Base: ${{ github.base_ref }}
            - Actor: ${{ github.actor }}

            Testing template escaping: {{ this should not be interpreted as a template }}
